import { Vehicle, Shop } from '../types';

export const MOCK_DEALERS: Shop[] = [
  {
    id: 'd1',
    ownerId: 'u1',
    name: 'Bhopal Motors',
    description: 'Trusted dealer in Bhopal for over 10 years. We specialize in certified pre-owned luxury and budget cars. Our mission is to provide quality vehicles with complete transparency.',
    images: ['https://picsum.photos/seed/shop1/800/600'],
    latitude: 23.2599,
    longitude: 77.4126,
    address: 'MP Nagar Zone 1',
    city: 'Bhopal',
    state: 'Madhya Pradesh',
    pincode: '462011',
    phone: '+91 98765 43210',
    mapEmbedUrl: 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d14663.078972856012!2d77.42436853243174!3d23.2515091705608!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x397c424056024197%3A0xe54d8520ec71597f!2sM%20P%20Nagar%2C%20Bhopal%2C%20Madhya%20Pradesh!5e0!3m2!1sen!2sin!4v1714234500000!5m2!1sen!2sin',
    verificationStatus: 'verified',
    isPremium: true,
    rating: 4.8,
    reviewsCount: 124,
    reviews: [
      {
        id: 'r1',
        userId: 'u101',
        userName: 'Rahul Sharma',
        rating: 5,
        comment: 'Excellent service! Bought a Swift last month and the experience was seamless. Highly recommended.',
        createdAt: '2024-03-15T10:00:00Z'
      },
      {
        id: 'r2',
        userId: 'u102',
        userName: 'Priya Singh',
        rating: 4,
        comment: 'Good collection of cars. The staff is very helpful. Price was slightly higher but the quality is top-notch.',
        createdAt: '2024-03-10T14:30:00Z'
      },
      {
        id: 'r3',
        userId: 'u103',
        userName: 'Amit Patel',
        rating: 5,
        comment: 'Best dealer in Bhopal. Transparent pricing and genuine vehicles.',
        createdAt: '2024-02-28T09:15:00Z'
      }
    ],
    createdAt: new Date().toISOString(),
  },
  {
    id: 'd2',
    ownerId: 'u2',
    name: 'Patna Wheels',
    description: 'Best collection of pre-owned bikes and cars in Patna. We offer easy financing and exchange options. Visit us for the best deals in Bihar.',
    images: ['https://picsum.photos/seed/shop2/800/600'],
    latitude: 25.5941,
    longitude: 85.1376,
    address: 'Boring Road',
    city: 'Patna',
    state: 'Bihar',
    pincode: '800001',
    phone: '+91 87654 32109',
    verificationStatus: 'verified',
    rating: 4.5,
    reviewsCount: 89,
    reviews: [
      {
        id: 'r4',
        userId: 'u104',
        userName: 'Vikram Kumar',
        rating: 5,
        comment: 'Found my dream bike here! Great prices and quick documentation.',
        createdAt: '2024-03-12T11:20:00Z'
      },
      {
        id: 'r5',
        userId: 'u105',
        userName: 'Soni Kumari',
        rating: 4,
        comment: 'Very professional behavior. They have a wide variety of choices.',
        createdAt: '2024-03-05T16:45:00Z'
      }
    ],
    createdAt: new Date().toISOString(),
  },
  {
    id: 'd3',
    ownerId: 'u3',
    name: 'Mumbai Elite Motors',
    description: 'Premier destination for supercars and luxury vehicles in South Mumbai. We deal exclusively in high-end exotics and performance cars.',
    images: ['https://images.unsplash.com/photo-1562141989-c5c79ac8f576?q=80&w=800&auto=format&fit=crop'],
    latitude: 18.9220,
    longitude: 72.8347,
    address: 'Worli Sea Face',
    city: 'Mumbai',
    state: 'Maharashtra',
    pincode: '400018',
    phone: '+91 99999 00001',
    verificationStatus: 'verified',
    isPremium: true,
    rating: 4.9,
    reviewsCount: 45,
    reviews: [],
    createdAt: new Date().toISOString(),
  },
  {
    id: 'd4',
    ownerId: 'u4',
    name: 'Bangalore Tech Wheels',
    description: 'Serving the tech capital with the best performance and luxury cars. Specialist in EV supercars and German engineering.',
    images: ['https://images.unsplash.com/photo-1552519507-da3b142c6e3d?q=80&w=800&auto=format&fit=crop'],
    latitude: 12.9716,
    longitude: 77.5946,
    address: 'Indiranagar 100ft Road',
    city: 'Bangalore',
    state: 'Karnataka',
    pincode: '560038',
    phone: '+91 99999 00002',
    verificationStatus: 'verified',
    isPremium: true,
    rating: 4.7,
    reviewsCount: 62,
    reviews: [],
    createdAt: new Date().toISOString(),
  },
  {
    id: 'd5',
    ownerId: 'u5',
    name: 'Raipur Roadstars',
    description: 'The biggest pre-owned car hub in Chhattisgarh. Specializing in SUVs and family cars with full service history.',
    images: ['https://images.unsplash.com/photo-1562141989-c5c79ac8f576?q=80&w=800&auto=format&fit=crop'],
    latitude: 21.2514,
    longitude: 81.6296,
    address: 'VIP Road',
    city: 'Raipur',
    state: 'Chhattisgarh',
    pincode: '492001',
    phone: '+91 99999 00003',
    verificationStatus: 'verified',
    rating: 4.6,
    reviewsCount: 38,
    reviews: [],
    createdAt: new Date().toISOString(),
  },
  {
    id: 'd6',
    ownerId: 'u6',
    name: 'Delhi Luxe Auto',
    description: 'The capital\'s premier luxury car showroom. We house everything from German engineering to Italian exotics.',
    images: ['https://images.unsplash.com/photo-1562141989-c5c79ac8f576?q=80&w=800&auto=format&fit=crop'],
    latitude: 28.6139,
    longitude: 77.2090,
    address: 'Chanakyapuri, New Delhi',
    city: 'Delhi NCR',
    state: 'Delhi',
    pincode: '110021',
    phone: '+91 99999 00004',
    verificationStatus: 'verified',
    isPremium: true,
    rating: 4.8,
    reviewsCount: 55,
    reviews: [],
    createdAt: new Date().toISOString(),
  },
  {
    id: 'd7',
    ownerId: 'u7',
    name: 'Hyderabad High Wheels',
    description: 'Luxury and performance vehicles in the heart of Jubilee Hills. Specialist in high-performance EVs and SUVs.',
    images: ['https://images.unsplash.com/photo-1552519507-da3b142c6e3d?q=80&w=800&auto=format&fit=crop'],
    latitude: 17.4334,
    longitude: 78.4005,
    address: 'Jubilee Hills Check Post',
    city: 'Hyderabad',
    state: 'Telangana',
    pincode: '500033',
    phone: '+91 99999 00005',
    verificationStatus: 'verified',
    isPremium: true,
    rating: 4.7,
    reviewsCount: 42,
    reviews: [],
    createdAt: new Date().toISOString(),
  },
  {
    id: 'd8',
    ownerId: 'u8',
    name: 'Chennai Classic & Exotic',
    description: 'Bringing global standards to Chennai. A curated collection of luxury sedans and premium SUVs.',
    images: ['https://images.unsplash.com/photo-1582510003544-4d00b7f74220?q=80&w=800&auto=format&fit=crop'],
    latitude: 13.0827,
    longitude: 80.2707,
    address: 'Anna Salai, Chennai',
    city: 'Chennai',
    state: 'Tamil Nadu',
    pincode: '600002',
    phone: '+91 99999 00006',
    verificationStatus: 'verified',
    rating: 4.5,
    reviewsCount: 29,
    reviews: [],
    createdAt: new Date().toISOString(),
  },
  {
    id: 'd9',
    ownerId: 'u9',
    name: 'Pune Performance',
    description: 'Enthusiast-driven car showroom in the automotive hub of India. We know our engines.',
    images: ['https://images.unsplash.com/photo-1566552881560-0be862a7c445?q=80&w=800&auto=format&fit=crop'],
    latitude: 18.5204,
    longitude: 73.8567,
    address: 'Baner Road, Pune',
    city: 'Pune',
    state: 'Maharashtra',
    pincode: '411045',
    phone: '+91 99999 00007',
    verificationStatus: 'verified',
    rating: 4.6,
    reviewsCount: 34,
    reviews: [],
    createdAt: new Date().toISOString(),
  }
];

export const MOCK_VEHICLES: Vehicle[] = [
  {
    id: 'v55',
    sellerId: 'u6',
    shopId: 'd6',
    title: 'Mercedes-AMG GT 4-Door Coupe',
    description: 'The executive rocket. Graphite Grey, performance seats, carbon fiber trim. Unrivaled road presence.',
    price: 26500000,
    vehicleType: 'car',
    brand: 'Mercedes-Benz',
    model: 'AMG GT',
    year: 2022,
    fuelType: 'petrol',
    transmission: 'automatic',
    kilometersDriven: 6200,
    ownership: '1st',
    city: 'Delhi NCR',
    state: 'Delhi',
    images: ['https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?q=80&w=1200&auto=format&fit=crop'],
    status: 'active',
    isFeatured: true,
    isVerified: true,
    verificationStatus: 'verified',
    listingType: 'premium',
    viewsCount: 12500,
    clicksCount: 1200,
    leadsCount: 25,
    priorityScore: 150,
    createdAt: new Date().toISOString(),
    registrationNumber: 'DL1-GT-6363',
    mileage: '7 kmpl',
    color: 'Graphite Grey',
    assemblyType: 'Imported',
  },
  {
    id: 'v56',
    sellerId: 'u6',
    shopId: 'd6',
    title: 'Audi e-tron GT RS',
    description: 'Electric performance reinvented. Tactical Green, performance sound, matrix LED headlamps. Luxury meets electric.',
    price: 19500000,
    vehicleType: 'car',
    brand: 'Audi',
    model: 'e-tron GT',
    year: 2023,
    fuelType: 'electric',
    transmission: 'automatic',
    kilometersDriven: 1500,
    ownership: '1st',
    city: 'Delhi NCR',
    state: 'Delhi',
    images: ['https://images.unsplash.com/photo-1614164185128-e4ec99c436d7?q=80&w=1200&auto=format&fit=crop'],
    status: 'active',
    isFeatured: true,
    isVerified: true,
    verificationStatus: 'verified',
    listingType: 'sponsored',
    viewsCount: 18000,
    clicksCount: 2200,
    leadsCount: 45,
    priorityScore: 180,
    createdAt: new Date().toISOString(),
    registrationNumber: 'DL1-EV-1000',
    mileage: '480 km/charge',
    color: 'Tactical Green',
    assemblyType: 'Imported',
  },
  {
    id: 'v57',
    sellerId: 'u7',
    shopId: 'd7',
    title: 'Porsche Macan GTS',
    description: 'The sports car of SUVs. Python Green, sport chrono package, air suspension. Performance in a compact package.',
    price: 13500000,
    vehicleType: 'car',
    brand: 'Porsche',
    model: 'Macan',
    year: 2022,
    fuelType: 'petrol',
    transmission: 'automatic',
    kilometersDriven: 8500,
    ownership: '1st',
    city: 'Hyderabad',
    state: 'Telangana',
    images: ['https://images.unsplash.com/photo-1544636331-e26879cd4d9b?q=80&w=1200&auto=format&fit=crop'],
    status: 'active',
    isFeatured: true,
    isVerified: true,
    verificationStatus: 'verified',
    listingType: 'premium',
    viewsCount: 6500,
    clicksCount: 850,
    leadsCount: 15,
    priorityScore: 140,
    createdAt: new Date().toISOString(),
    registrationNumber: 'TS09-M-9999',
    mileage: '9 kmpl',
    color: 'Python Green',
    assemblyType: 'Imported',
  },
  {
    id: 'v58',
    sellerId: 'u7',
    shopId: 'd7',
    title: 'BMW iX xDrive50',
    description: 'Electric luxury redefined. Aventurine Red, Bowers & Wilkins sound, crystal theme interior. The ultimate luxury EV SUV.',
    price: 12500000,
    vehicleType: 'car',
    brand: 'BMW',
    model: 'iX',
    year: 2023,
    fuelType: 'electric',
    transmission: 'automatic',
    kilometersDriven: 2200,
    ownership: '1st',
    city: 'Hyderabad',
    state: 'Telangana',
    images: ['https://images.unsplash.com/photo-1555215695-3004980ad54e?q=80&w=1200&auto=format&fit=crop'],
    status: 'active',
    isFeatured: true,
    isVerified: true,
    verificationStatus: 'verified',
    listingType: 'sponsored',
    viewsCount: 9200,
    clicksCount: 1100,
    leadsCount: 20,
    priorityScore: 140,
    createdAt: new Date().toISOString(),
    registrationNumber: 'TS09-IX-0001',
    mileage: '600 km/charge',
    color: 'Aventurine Red',
    assemblyType: 'Imported',
  },
  {
    id: 'v59',
    sellerId: 'u8',
    shopId: 'd8',
    title: 'Lexus LS 500h',
    description: 'Omotenashi luxury. Sonic Quartz, Kiriko glass interior, multi-stage hybrid. The quietest hybrid sedan.',
    price: 18500000,
    vehicleType: 'car',
    brand: 'Lexus',
    model: 'LS',
    year: 2022,
    fuelType: 'hybrid',
    transmission: 'automatic',
    kilometersDriven: 5400,
    ownership: '1st',
    city: 'Chennai',
    state: 'Tamil Nadu',
    images: ['https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?q=80&w=1200&auto=format&fit=crop'],
    status: 'active',
    isFeatured: true,
    isVerified: true,
    verificationStatus: 'verified',
    listingType: 'premium',
    viewsCount: 4200,
    clicksCount: 450,
    leadsCount: 10,
    priorityScore: 130,
    createdAt: new Date().toISOString(),
    registrationNumber: 'TN01-LS-5000',
    mileage: '15 kmpl',
    color: 'Sonic Quartz',
    assemblyType: 'Imported',
  },
  {
    id: 'v60',
    sellerId: 'u8',
    shopId: 'd8',
    title: 'Volvo S90 B5',
    description: 'Scandinavian minimalist luxury. Crystal White, Nappa leather, massage seats. Safety and elegance combined.',
    price: 6800000,
    vehicleType: 'car',
    brand: 'Volvo',
    model: 'S90',
    year: 2021,
    fuelType: 'petrol',
    transmission: 'automatic',
    kilometersDriven: 12500,
    ownership: '1st',
    city: 'Chennai',
    state: 'Tamil Nadu',
    images: ['https://images.unsplash.com/photo-1605515298946-d062f2e9da53?q=80&w=1200&auto=format&fit=crop'],
    status: 'active',
    isFeatured: false,
    isVerified: true,
    verificationStatus: 'verified',
    listingType: 'free',
    viewsCount: 3100,
    clicksCount: 280,
    leadsCount: 5,
    priorityScore: 60,
    createdAt: new Date().toISOString(),
    registrationNumber: 'TN01-S90-1122',
    mileage: '14 kmpl',
    color: 'White',
    assemblyType: 'Local',
  },
  {
    id: 'v61',
    sellerId: 'u9',
    shopId: 'd9',
    title: 'BMW M3 Competition',
    description: 'The driver\'s car. Isle of Man Green, carbon ceramic brakes, drift analyzer. Pure performance.',
    price: 14500000,
    vehicleType: 'car',
    brand: 'BMW',
    model: 'M3',
    year: 2022,
    fuelType: 'petrol',
    transmission: 'automatic',
    kilometersDriven: 4500,
    ownership: '1st',
    city: 'Pune',
    state: 'Maharashtra',
    images: ['https://images.unsplash.com/photo-1555215695-3004980ad54e?q=80&w=1200&auto=format&fit=crop'],
    status: 'active',
    isFeatured: true,
    isVerified: true,
    verificationStatus: 'verified',
    listingType: 'premium',
    viewsCount: 15600,
    clicksCount: 1800,
    leadsCount: 38,
    priorityScore: 190,
    createdAt: new Date().toISOString(),
    registrationNumber: 'MH12-M3-0001',
    mileage: '8 kmpl',
    color: 'Isle of Man Green',
    assemblyType: 'Imported',
  },
  {
    id: 'v62',
    sellerId: 'u9',
    shopId: 'd9',
    title: 'Mercedes-Benz GLE 450 AMG',
    description: 'Sporty luxury SUV. Selenite Grey, AMG line, Burmester sound. The perfect all-rounder.',
    price: 11500000,
    vehicleType: 'car',
    brand: 'Mercedes-Benz',
    model: 'GLE',
    year: 2021,
    fuelType: 'petrol',
    transmission: 'automatic',
    kilometersDriven: 14000,
    ownership: '1st',
    city: 'Pune',
    state: 'Maharashtra',
    images: ['https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?q=80&w=1200&auto=format&fit=crop'],
    status: 'active',
    isFeatured: true,
    isVerified: true,
    verificationStatus: 'verified',
    listingType: 'sponsored',
    viewsCount: 8400,
    clicksCount: 950,
    leadsCount: 18,
    priorityScore: 145,
    createdAt: new Date().toISOString(),
    registrationNumber: 'MH12-GL-7788',
    mileage: '9 kmpl',
    color: 'Grey',
    assemblyType: 'Local',
  },
  {
    id: 'v63',
    sellerId: 'u8',
    shopId: 'd8',
    title: 'Jaguar I-PACE Black',
    description: 'Electric performance SUV. Eiger Grey, Black Pack, panoramic roof. Practical and fast.',
    price: 11000000,
    vehicleType: 'car',
    brand: 'Jaguar',
    model: 'I-PACE',
    year: 2022,
    fuelType: 'electric',
    transmission: 'automatic',
    kilometersDriven: 6500,
    ownership: '1st',
    city: 'Chennai',
    state: 'Tamil Nadu',
    images: ['https://images.unsplash.com/photo-1592198084033-aade902d1aae?q=80&w=1200&auto=format&fit=crop'],
    status: 'active',
    isFeatured: true,
    isVerified: true,
    verificationStatus: 'verified',
    listingType: 'premium',
    viewsCount: 5200,
    clicksCount: 680,
    leadsCount: 12,
    priorityScore: 125,
    createdAt: new Date().toISOString(),
    registrationNumber: 'TN02-EV-0001',
    mileage: '470 km/charge',
    color: 'Eiger Grey',
    assemblyType: 'Imported',
  },
  {
    id: 'v64',
    sellerId: 'u9',
    shopId: 'd9',
    title: 'Audi Q8 55 TFSI',
    description: 'The flagship SUV coupe. Dragon Orange, matrix headlights, virtual cockpit. Modern luxury.',
    price: 12500000,
    vehicleType: 'car',
    brand: 'Audi',
    model: 'Q8',
    year: 2021,
    fuelType: 'petrol',
    transmission: 'automatic',
    kilometersDriven: 11000,
    ownership: '1st',
    city: 'Pune',
    state: 'Maharashtra',
    images: ['https://images.unsplash.com/photo-1541899481282-d53bffe3c35d?q=80&w=1200&auto=format&fit=crop'],
    status: 'active',
    isFeatured: false,
    isVerified: true,
    verificationStatus: 'verified',
    listingType: 'free',
    viewsCount: 7800,
    clicksCount: 820,
    leadsCount: 15,
    priorityScore: 80,
    createdAt: new Date().toISOString(),
    registrationNumber: 'MH14-Q8-8888',
    mileage: '8 kmpl',
    color: 'Orange',
    assemblyType: 'Imported',
  },
  {
    id: 'v65',
    sellerId: 'u2',
    shopId: 'd2',
    title: 'Volkswagen Virtus GT',
    description: 'The driver\'s sedan. Wild Cherry Red, 1.5 TSI engine, DSG transmission. German engineering for India.',
    price: 1750000,
    vehicleType: 'car',
    brand: 'Volkswagen',
    model: 'Virtus',
    year: 2022,
    fuelType: 'petrol',
    transmission: 'automatic',
    kilometersDriven: 5200,
    ownership: '1st',
    city: 'Patna',
    state: 'Bihar',
    images: ['https://images.unsplash.com/photo-1617469767053-d3b523a0b982?q=80&w=1200&auto=format&fit=crop'],
    status: 'active',
    isFeatured: true,
    isVerified: true,
    verificationStatus: 'verified',
    listingType: 'premium',
    viewsCount: 9500,
    clicksCount: 1100,
    leadsCount: 22,
    priorityScore: 160,
    createdAt: new Date().toISOString(),
    registrationNumber: 'BR01-V-2000',
    mileage: '18 kmpl',
    color: 'Wild Cherry Red',
    assemblyType: 'Local',
  },
  {
    id: 'v66',
    sellerId: 'u5',
    shopId: 'd5',
    title: 'Mahindra XUV700 AX7L',
    description: 'The king of tech SUVs. AWD, diesel automatic, level 2 ADAS, Sony sound system.',
    price: 2450000,
    vehicleType: 'car',
    brand: 'Mahindra',
    model: 'XUV700',
    year: 2022,
    fuelType: 'diesel',
    transmission: 'automatic',
    kilometersDriven: 14500,
    ownership: '1st',
    city: 'Raipur',
    state: 'Chhattisgarh',
    images: ['https://images.unsplash.com/photo-1631195123280-9975f81f185d?q=80&w=1200&auto=format&fit=crop'],
    status: 'active',
    isFeatured: true,
    isVerified: true,
    verificationStatus: 'verified',
    listingType: 'premium',
    viewsCount: 14000,
    clicksCount: 1800,
    leadsCount: 42,
    priorityScore: 170,
    createdAt: new Date().toISOString(),
    registrationNumber: 'CG04-XUV-700',
    mileage: '13 kmpl',
    color: 'Midnight Blue',
    assemblyType: 'Local',
  },
  {
    id: 'v67',
    sellerId: 'u6',
    shopId: 'd6',
    title: 'Range Rover Sport SVR',
    description: 'The loudest SUV. Estoril Blue, performance bucket seats, carbon fiber hood. Pure brute force.',
    price: 18500000,
    vehicleType: 'car',
    brand: 'Land Rover',
    model: 'Range Rover Sport',
    year: 2021,
    fuelType: 'petrol',
    transmission: 'automatic',
    kilometersDriven: 12500,
    ownership: '1st',
    city: 'Delhi NCR',
    state: 'Delhi',
    images: ['https://images.unsplash.com/photo-1541899481282-d53bffe3c35d?q=80&w=1200&auto=format&fit=crop'],
    status: 'active',
    isFeatured: true,
    isVerified: true,
    verificationStatus: 'verified',
    listingType: 'premium',
    viewsCount: 7500,
    clicksCount: 920,
    leadsCount: 15,
    priorityScore: 135,
    createdAt: new Date().toISOString(),
    registrationNumber: 'DL3-SVR-007',
    mileage: '6 kmpl',
    color: 'Estoril Blue',
    assemblyType: 'Imported',
  },
  {
    id: 'v68',
    sellerId: 'u6',
    shopId: 'd6',
    title: 'Lexus RX 450hL',
    description: 'Luxury hybrid SUV. Sonic Titanium, Mark Levinson sound, 7-seater comfort. The intelligent choice.',
    price: 11500000,
    vehicleType: 'car',
    brand: 'Lexus',
    model: 'RX',
    year: 2022,
    fuelType: 'hybrid',
    transmission: 'automatic',
    kilometersDriven: 9500,
    ownership: '1st',
    city: 'Delhi NCR',
    state: 'Delhi',
    images: ['https://images.unsplash.com/photo-1621007947382-bb3c3994e3fb?q=80&w=1200&auto=format&fit=crop'],
    status: 'active',
    isFeatured: false,
    isVerified: true,
    verificationStatus: 'verified',
    listingType: 'free',
    viewsCount: 4200,
    clicksCount: 480,
    leadsCount: 6,
    priorityScore: 70,
    createdAt: new Date().toISOString(),
    registrationNumber: 'DL1-RX-4500',
    mileage: '16 kmpl',
    color: 'Titanium',
    assemblyType: 'Imported',
  },
  {
    id: 'v69',
    sellerId: 'u7',
    shopId: 'd7',
    title: 'BMW M5 CS',
    description: 'The ultimate super sedan. Frozen Deep Green, gold-bronze wheels, bucket seats. A legend reborn.',
    price: 21500000,
    vehicleType: 'car',
    brand: 'BMW',
    model: 'M5',
    year: 2022,
    fuelType: 'petrol',
    transmission: 'automatic',
    kilometersDriven: 3500,
    ownership: '1st',
    city: 'Hyderabad',
    state: 'Telangana',
    images: ['https://images.unsplash.com/photo-1555215695-3004980ad54e?q=80&w=1200&auto=format&fit=crop'],
    status: 'active',
    isFeatured: true,
    isVerified: true,
    verificationStatus: 'verified',
    listingType: 'premium',
    viewsCount: 14500,
    clicksCount: 2100,
    leadsCount: 38,
    priorityScore: 195,
    createdAt: new Date().toISOString(),
    registrationNumber: 'TS09-M5-CS',
    mileage: '7 kmpl',
    color: 'Frozen Green',
    assemblyType: 'Imported',
  },
  {
    id: 'v70',
    sellerId: 'u7',
    shopId: 'd7',
    title: 'Mercedes-Benz EQS 580',
    description: 'Electric luxury flagship. Nautic Blue, hyperscreen interior, 4MATIC. The most aerodynamic car.',
    price: 16500000,
    vehicleType: 'car',
    brand: 'Mercedes-Benz',
    model: 'EQS',
    year: 2023,
    fuelType: 'electric',
    transmission: 'automatic',
    kilometersDriven: 1100,
    ownership: '1st',
    city: 'Hyderabad',
    state: 'Telangana',
    images: ['https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?q=80&w=1200&auto=format&fit=crop'],
    status: 'active',
    isFeatured: true,
    isVerified: true,
    verificationStatus: 'verified',
    listingType: 'sponsored',
    viewsCount: 11200,
    clicksCount: 1400,
    leadsCount: 22,
    priorityScore: 155,
    createdAt: new Date().toISOString(),
    registrationNumber: 'TS09-EQ-580',
    mileage: '670 km/charge',
    color: 'Blue',
    assemblyType: 'Local',
  },
  {
    id: 'v71',
    sellerId: 'u8',
    shopId: 'd8',
    title: 'Porsche Cayenne Turbo',
    description: 'The master of all roads. Carrara White, sport design pack, premium leather. High-performance SUV.',
    price: 19500000,
    vehicleType: 'car',
    brand: 'Porsche',
    model: 'Cayenne',
    year: 2021,
    fuelType: 'petrol',
    transmission: 'automatic',
    kilometersDriven: 11400,
    ownership: '1st',
    city: 'Chennai',
    state: 'Tamil Nadu',
    images: ['https://images.unsplash.com/photo-1544636331-e26879cd4d9b?q=80&w=1200&auto=format&fit=crop'],
    status: 'active',
    isFeatured: true,
    isVerified: true,
    verificationStatus: 'verified',
    listingType: 'premium',
    viewsCount: 5600,
    clicksCount: 750,
    leadsCount: 12,
    priorityScore: 140,
    createdAt: new Date().toISOString(),
    registrationNumber: 'TN01-PC-1000',
    mileage: '8 kmpl',
    color: 'White',
    assemblyType: 'Imported',
  },
  {
    id: 'v72',
    sellerId: 'u8',
    shopId: 'd8',
    title: 'Land Rover Defender 110',
    description: 'Icons re-imagined. Pangea Green, explorer pack, robust interior. The ultimate adventure vehicle.',
    price: 12500000,
    vehicleType: 'car',
    brand: 'Land Rover',
    model: 'Defender',
    year: 2022,
    fuelType: 'diesel',
    transmission: 'automatic',
    kilometersDriven: 8200,
    ownership: '1st',
    city: 'Chennai',
    state: 'Tamil Nadu',
    images: ['https://images.unsplash.com/photo-1503376780353-7e6692767b70?q=80&w=1200&auto=format&fit=crop'],
    status: 'active',
    isFeatured: true,
    isVerified: true,
    verificationStatus: 'verified',
    listingType: 'sponsored',
    viewsCount: 15000,
    clicksCount: 2400,
    leadsCount: 55,
    priorityScore: 195,
    createdAt: new Date().toISOString(),
    registrationNumber: 'TN01-LR-110',
    mileage: '11 kmpl',
    color: 'Pangea Green',
    assemblyType: 'Imported',
  },
  {
    id: 'v73',
    sellerId: 'u9',
    shopId: 'd9',
    title: 'Jaguar XF S',
    description: 'Business with pleasure. Portofino Blue, Windsor leather seats, Meridian sound system.',
    price: 6500000,
    vehicleType: 'car',
    brand: 'Jaguar',
    model: 'XF',
    year: 2021,
    fuelType: 'diesel',
    transmission: 'automatic',
    kilometersDriven: 18500,
    ownership: '1st',
    city: 'Pune',
    state: 'Maharashtra',
    images: ['https://images.unsplash.com/photo-1592198084033-aade902d1aae?q=80&w=1200&auto=format&fit=crop'],
    status: 'active',
    isFeatured: false,
    isVerified: true,
    verificationStatus: 'verified',
    listingType: 'free',
    viewsCount: 3800,
    clicksCount: 420,
    leadsCount: 8,
    priorityScore: 40,
    createdAt: new Date().toISOString(),
    registrationNumber: 'MH12-XF-5588',
    mileage: '14 kmpl',
    color: 'Blue',
    assemblyType: 'Local',
  },
  {
    id: 'v74',
    sellerId: 'u9',
    shopId: 'd9',
    title: 'Audi RS5 Sportback',
    description: 'The sharpest coupe. Sonoma Green, performance package, carbon interior. Brutal acceleration.',
    price: 11000000,
    vehicleType: 'car',
    brand: 'Audi',
    model: 'RS5',
    year: 2021,
    fuelType: 'petrol',
    transmission: 'automatic',
    kilometersDriven: 8900,
    ownership: '1st',
    city: 'Pune',
    state: 'Maharashtra',
    images: ['https://images.unsplash.com/photo-1541899481282-d53bffe3c35d?q=80&w=1200&auto=format&fit=crop'],
    status: 'active',
    isFeatured: true,
    isVerified: true,
    verificationStatus: 'verified',
    listingType: 'premium',
    viewsCount: 9200,
    clicksCount: 1100,
    leadsCount: 20,
    priorityScore: 150,
    createdAt: new Date().toISOString(),
    registrationNumber: 'MH12-RS-500',
    mileage: '9 kmpl',
    color: 'Sonoma Green',
    assemblyType: 'Imported',
  },
  {
    id: 'v75',
    sellerId: 'u1',
    shopId: 'd1',
    title: 'Toyota Fortuner Legender',
    description: 'The real SUV. 4x4, white with black roof, JBL sound system. High road presence.',
    price: 4800000,
    vehicleType: 'car',
    brand: 'Toyota',
    model: 'Fortuner',
    year: 2022,
    fuelType: 'diesel',
    transmission: 'automatic',
    kilometersDriven: 16500,
    ownership: '1st',
    city: 'Bhopal',
    state: 'Madhya Pradesh',
    images: ['https://images.unsplash.com/photo-1621007947382-bb3c3994e3fb?q=80&w=1200&auto=format&fit=crop'],
    status: 'active',
    isFeatured: true,
    isVerified: true,
    verificationStatus: 'verified',
    listingType: 'premium',
    viewsCount: 12500,
    clicksCount: 1800,
    leadsCount: 35,
    priorityScore: 175,
    createdAt: new Date().toISOString(),
    registrationNumber: 'MP04-FL-0001',
    mileage: '12 kmpl',
    color: 'White',
    assemblyType: 'Local',
  },
  {
    id: 'v20',
    sellerId: 'u3',
    shopId: 'd3',
    title: 'Lamborghini Huracan EVO',
    description: 'V10 power, Arancio Borealis (Orange) color, life-time ceramic coating, barely driven. A true masterpiece of Italian engineering.',
    price: 38000000,
    vehicleType: 'car',
    brand: 'Lamborghini',
    model: 'Huracan',
    year: 2022,
    fuelType: 'petrol',
    transmission: 'automatic',
    kilometersDriven: 2500,
    ownership: '1st',
    city: 'Mumbai',
    state: 'Maharashtra',
    images: ['https://images.unsplash.com/photo-1544636331-e26879cd4d9b?q=80&w=1200&auto=format&fit=crop', 'https://images.unsplash.com/photo-1511919884226-fd3cad34687c?q=80&w=1200&auto=format&fit=crop'],
    status: 'active',
    isFeatured: true,
    isVerified: true,
    verificationStatus: 'verified',
    listingType: 'sponsored',
    viewsCount: 15400,
    clicksCount: 2100,
    leadsCount: 45,
    priorityScore: 200,
    createdAt: new Date().toISOString(),
    registrationNumber: 'MH01-EX-0001',
    mileage: '6 kmpl',
    color: 'Orange',
    assemblyType: 'Imported',
  },
  {
    id: 'v21',
    sellerId: 'u4',
    shopId: 'd4',
    title: 'Porsche 911 Carrera S',
    description: 'The ultimate daily supercar. Guards Red, Sport Chrono Package, sunroof, Bose sound system. Perfect condition.',
    price: 18500000,
    vehicleType: 'car',
    brand: 'Porsche',
    model: '911',
    year: 2021,
    fuelType: 'petrol',
    transmission: 'automatic',
    kilometersDriven: 8500,
    ownership: '1st',
    city: 'Bangalore',
    state: 'Karnataka',
    images: ['https://images.unsplash.com/photo-1503376780353-7e6692767b70?q=80&w=1200&auto=format&fit=crop', 'https://images.unsplash.com/photo-1614164185128-e4ec99c436d7?q=80&w=1200&auto=format&fit=crop'],
    status: 'active',
    isFeatured: true,
    isVerified: true,
    verificationStatus: 'verified',
    listingType: 'premium',
    viewsCount: 9800,
    clicksCount: 1500,
    leadsCount: 32,
    priorityScore: 180,
    createdAt: new Date().toISOString(),
    registrationNumber: 'KA51-PH-9999',
    mileage: '9 kmpl',
    color: 'Red',
    assemblyType: 'Imported',
  },
  {
    id: 'v22',
    sellerId: 'u3',
    shopId: 'd3',
    title: 'Ferrari F8 Tributo',
    description: 'Rosso Corsa, carbon fiber interior, racing seats. Only 1500km on the clock. Still under factory warranty.',
    price: 45000000,
    vehicleType: 'car',
    brand: 'Ferrari',
    model: 'F8 Tributo',
    year: 2023,
    fuelType: 'petrol',
    transmission: 'automatic',
    kilometersDriven: 1500,
    ownership: '1st',
    city: 'Mumbai',
    state: 'Maharashtra',
    images: ['https://images.unsplash.com/photo-1592198084033-aade902d1aae?q=80&w=1200&auto=format&fit=crop', 'https://images.unsplash.com/photo-1583121274602-15f1f9191919?q=80&w=1200&auto=format&fit=crop'],
    status: 'active',
    isFeatured: true,
    isVerified: true,
    verificationStatus: 'verified',
    listingType: 'sponsored',
    viewsCount: 22000,
    clicksCount: 3500,
    leadsCount: 18,
    priorityScore: 250,
    createdAt: new Date().toISOString(),
    registrationNumber: 'MH04-FR-0008',
    mileage: '5 kmpl',
    color: 'Rosso Corsa (Red)',
    assemblyType: 'Imported',
  },
  {
    id: 'v23',
    sellerId: 'u4',
    shopId: 'd4',
    title: 'Audi R8 V10 Performance',
    description: 'Naturally aspirated V10, Quattro AWD, carbon sigma side blades. One of the last pure V10s in the country.',
    price: 26000000,
    vehicleType: 'car',
    brand: 'Audi',
    model: 'R8',
    year: 2020,
    fuelType: 'petrol',
    transmission: 'automatic',
    kilometersDriven: 11000,
    ownership: '1st',
    city: 'Bangalore',
    state: 'Karnataka',
    images: ['https://images.unsplash.com/photo-1605559424843-9e4c228bf1c2?q=80&w=1200&auto=format&fit=crop', 'https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?q=80&w=1200&auto=format&fit=crop'],
    status: 'active',
    isFeatured: true,
    isVerified: true,
    verificationStatus: 'verified',
    listingType: 'premium',
    viewsCount: 7500,
    clicksCount: 900,
    leadsCount: 15,
    priorityScore: 160,
    createdAt: new Date().toISOString(),
    registrationNumber: 'KA03-R8-0010',
    mileage: '7 kmpl',
    color: 'Vegas Yellow',
    assemblyType: 'Imported',
  },
  {
    id: 'v24',
    sellerId: 'u3',
    shopId: 'd3',
    title: 'Mercedes-Maybach S-Class',
    description: 'The pinnacle of luxury. First-class cabin, massage seats, dual-tone paint. Business on wheels.',
    price: 28000000,
    vehicleType: 'car',
    brand: 'Mercedes-Benz',
    model: 'Maybach S680',
    year: 2022,
    fuelType: 'petrol',
    transmission: 'automatic',
    kilometersDriven: 4500,
    ownership: '1st',
    city: 'Mumbai',
    state: 'Maharashtra',
    images: ['https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?q=80&w=1200&auto=format&fit=crop', 'https://images.unsplash.com/photo-1552519507-da3b142c6e3d?q=80&w=1200&auto=format&fit=crop'],
    status: 'active',
    isFeatured: true,
    isVerified: true,
    verificationStatus: 'verified',
    listingType: 'sponsored',
    viewsCount: 12000,
    clicksCount: 1400,
    leadsCount: 32,
    priorityScore: 190,
    createdAt: new Date().toISOString(),
    registrationNumber: 'MH01-MM-0001',
    mileage: '8 kmpl',
    color: 'Obsidian Black over Selenite Grey',
    assemblyType: 'Imported',
  },
  {
    id: 'v25',
    sellerId: 'u4',
    shopId: 'd4',
    title: 'Tesla Model S Plaid',
    description: 'Triple motor setup, 1020 HP, 0-100 in 2.1s. Carbon fiber interior, yoke steering. Future of mobility.',
    price: 14500000,
    vehicleType: 'car',
    brand: 'Tesla',
    model: 'Model S',
    year: 2023,
    fuelType: 'electric',
    transmission: 'automatic',
    kilometersDriven: 1200,
    ownership: '1st',
    city: 'Bangalore',
    state: 'Karnataka',
    images: ['https://images.unsplash.com/photo-1560958089-b8a1929cea89?q=80&w=1200&auto=format&fit=crop'],
    status: 'active',
    isFeatured: true,
    isVerified: true,
    verificationStatus: 'verified',
    listingType: 'premium',
    viewsCount: 25000,
    clicksCount: 3200,
    leadsCount: 68,
    priorityScore: 220,
    createdAt: new Date().toISOString(),
    registrationNumber: 'KA05-EV-0001',
    mileage: '600 km/charge',
    color: 'Solid Black',
    assemblyType: 'Imported',
  },
  {
    id: 'v26',
    sellerId: 'u3',
    shopId: 'd3',
    title: 'BMW M8 Coupe',
    description: 'Marina Bay Blue, Competition Package, Bowers & Wilkins sound. A grand tourer with supercar performance.',
    price: 19500000,
    vehicleType: 'car',
    brand: 'BMW',
    model: 'M8',
    year: 2021,
    fuelType: 'petrol',
    transmission: 'automatic',
    kilometersDriven: 6800,
    ownership: '1st',
    city: 'Mumbai',
    state: 'Maharashtra',
    images: ['https://images.unsplash.com/photo-1555215695-3004980ad54e?q=80&w=1200&auto=format&fit=crop'],
    status: 'active',
    isFeatured: false,
    isVerified: true,
    verificationStatus: 'verified',
    listingType: 'free',
    viewsCount: 8500,
    clicksCount: 920,
    leadsCount: 15,
    priorityScore: 85,
    createdAt: new Date().toISOString(),
    registrationNumber: 'MH01-M8-COMP',
    mileage: '8 kmpl',
    color: 'Marina Bay Blue',
    assemblyType: 'Imported',
  },
  {
    id: 'v27',
    sellerId: 'u3',
    shopId: 'd3',
    title: 'Land Rover Range Rover Vogue',
    description: 'The definitive luxury SUV. Santorini Black, Pivi Pro, 22-inch wheels. Ultimate comfort and off-road capability.',
    price: 22000000,
    vehicleType: 'car',
    brand: 'Land Rover',
    model: 'Range Rover',
    year: 2021,
    fuelType: 'diesel',
    transmission: 'automatic',
    kilometersDriven: 14500,
    ownership: '1st',
    city: 'Mumbai',
    state: 'Maharashtra',
    images: ['https://images.unsplash.com/photo-1503376780353-7e6692767b70?q=80&w=1200&auto=format&fit=crop'],
    status: 'active',
    isFeatured: true,
    isVerified: true,
    verificationStatus: 'verified',
    listingType: 'premium',
    viewsCount: 6200,
    clicksCount: 740,
    leadsCount: 11,
    priorityScore: 125,
    createdAt: new Date().toISOString(),
    registrationNumber: 'MH04-RR-1000',
    mileage: '10 kmpl',
    color: 'Black',
    assemblyType: 'Imported',
  },
  {
    id: 'v28',
    sellerId: 'u4',
    shopId: 'd4',
    title: 'BMW X7 xDrive40i',
    description: '7-seater luxury SUV. Mineral White, laser lights, sky lounge sunroof. Perfect for family luxury travel.',
    price: 13500000,
    vehicleType: 'car',
    brand: 'BMW',
    model: 'X7',
    year: 2022,
    fuelType: 'petrol',
    transmission: 'automatic',
    kilometersDriven: 9200,
    ownership: '1st',
    city: 'Bangalore',
    state: 'Karnataka',
    images: ['https://images.unsplash.com/photo-1555215695-3004980ad54e?q=80&w=1200&auto=format&fit=crop'],
    status: 'active',
    isFeatured: true,
    isVerified: true,
    verificationStatus: 'verified',
    listingType: 'sponsored',
    viewsCount: 5400,
    clicksCount: 650,
    leadsCount: 12,
    priorityScore: 140,
    createdAt: new Date().toISOString(),
    registrationNumber: 'KA03-X7-7777',
    mileage: '8 kmpl',
    color: 'White',
    assemblyType: 'Local',
  },
  {
    id: 'v29',
    sellerId: 'u3',
    shopId: 'd3',
    title: 'Porsche Panamera Turbo',
    description: 'Four-door performance. Night Blue Metallic, rear seat entertainment, sport exhaust. Supercar speed with sedan comfort.',
    price: 21000000,
    vehicleType: 'car',
    brand: 'Porsche',
    model: 'Panamera',
    year: 2020,
    fuelType: 'petrol',
    transmission: 'automatic',
    kilometersDriven: 11000,
    ownership: '1st',
    city: 'Mumbai',
    state: 'Maharashtra',
    images: ['https://images.unsplash.com/photo-1503376780353-7e6692767b70?q=80&w=1200&auto=format&fit=crop'],
    status: 'active',
    isFeatured: false,
    isVerified: true,
    verificationStatus: 'verified',
    listingType: 'premium',
    viewsCount: 4200,
    clicksCount: 510,
    leadsCount: 9,
    priorityScore: 110,
    createdAt: new Date().toISOString(),
    registrationNumber: 'MH01-PP-4444',
    mileage: '8 kmpl',
    color: 'Night Blue',
    assemblyType: 'Imported',
  },
  {
    id: 'v30',
    sellerId: 'u4',
    shopId: 'd4',
    title: 'Mercedes-Benz G-Wagon G63 AMG',
    description: 'The legendary off-roader. Obsidian Black, red leather interior, side-exit exhausts. Unmatched presence on the road.',
    price: 32000000,
    vehicleType: 'car',
    brand: 'Mercedes-Benz',
    model: 'G-Class',
    year: 2021,
    fuelType: 'petrol',
    transmission: 'automatic',
    kilometersDriven: 7500,
    ownership: '1st',
    city: 'Bangalore',
    state: 'Karnataka',
    images: ['https://images.unsplash.com/photo-1552519507-da3b142c6e3d?q=80&w=1200&auto=format&fit=crop'],
    status: 'active',
    isFeatured: true,
    isVerified: true,
    verificationStatus: 'verified',
    listingType: 'sponsored',
    viewsCount: 18000,
    clicksCount: 2200,
    leadsCount: 45,
    priorityScore: 200,
    createdAt: new Date().toISOString(),
    registrationNumber: 'KA01-G63-0001',
    mileage: '6 kmpl',
    color: 'Black',
    assemblyType: 'Imported',
  },
  {
    id: 'v31',
    sellerId: 'u3',
    shopId: 'd3',
    title: 'Jaguar F-Type R',
    description: 'Pure adrenaline. British Racing Green, V8 supercharged engine, active exhaust. Hear it roar.',
    price: 11500000,
    vehicleType: 'car',
    brand: 'Jaguar',
    model: 'F-Type',
    year: 2019,
    fuelType: 'petrol',
    transmission: 'automatic',
    kilometersDriven: 14000,
    ownership: '2nd',
    city: 'Mumbai',
    state: 'Maharashtra',
    images: ['https://images.unsplash.com/photo-1592198084033-aade902d1aae?q=80&w=1200&auto=format&fit=crop'],
    status: 'active',
    isFeatured: true,
    isVerified: true,
    verificationStatus: 'verified',
    listingType: 'featured',
    viewsCount: 9500,
    clicksCount: 820,
    leadsCount: 15,
    priorityScore: 75,
    createdAt: new Date().toISOString(),
    registrationNumber: 'MH02-FT-8888',
    mileage: '7 kmpl',
    color: 'British Racing Green',
    assemblyType: 'Imported',
  },
  {
    id: 'v32',
    sellerId: 'u4',
    shopId: 'd4',
    title: 'Skoda Octavia RS 245',
    description: 'The enthusiast choice. Steel Grey, Alcantara seats, stage 1 tuned for 290hp. Sleeper performance.',
    price: 3600000,
    vehicleType: 'car',
    brand: 'Skoda',
    model: 'Octavia RS',
    year: 2020,
    fuelType: 'petrol',
    transmission: 'automatic',
    kilometersDriven: 22000,
    ownership: '1st',
    city: 'Bangalore',
    state: 'Karnataka',
    images: ['https://images.unsplash.com/photo-1567818735868-e71b99932e29?q=80&w=1200&auto=format&fit=crop'],
    status: 'active',
    isFeatured: false,
    isVerified: true,
    verificationStatus: 'verified',
    listingType: 'free',
    viewsCount: 12000,
    clicksCount: 1100,
    leadsCount: 22,
    priorityScore: 50,
    createdAt: new Date().toISOString(),
    registrationNumber: 'KA51-RS-245',
    mileage: '11 kmpl',
    color: 'Steel Grey',
    assemblyType: 'Imported',
  },
  {
    id: 'v33',
    sellerId: 'u3',
    shopId: 'd3',
    title: 'Toyota Vellfire Executive Lounge',
    description: 'First class on the road. Pearl White, recliner seats with massage, perfect for VVIP transport.',
    price: 9500000,
    vehicleType: 'car',
    brand: 'Toyota',
    model: 'Vellfire',
    year: 2021,
    fuelType: 'hybrid',
    transmission: 'automatic',
    kilometersDriven: 18000,
    ownership: '1st',
    city: 'Mumbai',
    state: 'Maharashtra',
    images: ['https://images.unsplash.com/photo-1621007947382-bb3c3994e3fb?q=80&w=1200&auto=format&fit=crop'],
    status: 'active',
    isFeatured: true,
    isVerified: true,
    verificationStatus: 'verified',
    listingType: 'premium',
    viewsCount: 7800,
    clicksCount: 850,
    leadsCount: 14,
    priorityScore: 120,
    createdAt: new Date().toISOString(),
    registrationNumber: 'MH43-VF-9999',
    mileage: '16 kmpl',
    color: 'Pearl White',
    assemblyType: 'Imported',
  },
  {
    id: 'v34',
    sellerId: 'u4',
    shopId: 'd4',
    title: 'Volvo XC90 Recharge',
    description: 'Sustainability meets luxury. Plug-in hybrid, air suspension, Bowers & Wilkins sound. Ultimate safety.',
    price: 8500000,
    vehicleType: 'car',
    brand: 'Volvo',
    model: 'XC90',
    year: 2022,
    fuelType: 'hybrid',
    transmission: 'automatic',
    kilometersDriven: 12500,
    ownership: '1st',
    city: 'Bangalore',
    state: 'Karnataka',
    images: ['https://images.unsplash.com/photo-1605515298946-d062f2e9da53?q=80&w=1200&auto=format&fit=crop'],
    status: 'active',
    isFeatured: false,
    isVerified: true,
    verificationStatus: 'verified',
    listingType: 'free',
    viewsCount: 5200,
    clicksCount: 580,
    leadsCount: 8,
    priorityScore: 45,
    createdAt: new Date().toISOString(),
    registrationNumber: 'KA01-XC-9000',
    mileage: '18 kmpl (ext 40km range)',
    color: 'Crystal White',
    assemblyType: 'Local',
  },
  {
    id: 'v35',
    sellerId: 'u3',
    shopId: 'd3',
    title: 'Audi RS7 Sportback',
    description: 'V8 twin-turbo beast. Nardo Grey, RS dynamic package, ceramic brakes. 0-100 in 3.6 seconds.',
    price: 16500000,
    vehicleType: 'car',
    brand: 'Audi',
    model: 'RS7',
    year: 2021,
    fuelType: 'petrol',
    transmission: 'automatic',
    kilometersDriven: 8200,
    ownership: '1st',
    city: 'Mumbai',
    state: 'Maharashtra',
    images: ['https://images.unsplash.com/photo-1541899481282-d53bffe3c35d?q=80&w=1200&auto=format&fit=crop'],
    status: 'active',
    isFeatured: true,
    isVerified: true,
    verificationStatus: 'verified',
    listingType: 'sponsored',
    viewsCount: 11000,
    clicksCount: 1400,
    leadsCount: 25,
    priorityScore: 165,
    createdAt: new Date().toISOString(),
    registrationNumber: 'MH01-RS-0007',
    mileage: '8 kmpl',
    color: 'Nardo Grey',
    assemblyType: 'Imported',
  },
  {
    id: 'v36',
    sellerId: 'u4',
    shopId: 'd4',
    title: 'MG ZS EV Exclusive',
    description: 'Electric SUV for the city. Aurora Silver, panoramic sunroof, i-SMART tech. Zero emissions.',
    price: 2200000,
    vehicleType: 'car',
    brand: 'MG',
    model: 'ZS EV',
    year: 2022,
    fuelType: 'electric',
    transmission: 'automatic',
    kilometersDriven: 15400,
    ownership: '1st',
    city: 'Bangalore',
    state: 'Karnataka',
    images: ['https://images.unsplash.com/photo-1593941707882-a5bba14938c7?q=80&w=1200&auto=format&fit=crop'],
    status: 'active',
    isFeatured: true,
    isVerified: true,
    verificationStatus: 'verified',
    listingType: 'premium',
    viewsCount: 6500,
    clicksCount: 1200,
    leadsCount: 25,
    priorityScore: 130,
    createdAt: new Date().toISOString(),
    registrationNumber: 'KA03-MG-4444',
    mileage: '419 km/charge',
    color: 'Aurora Silver',
    assemblyType: 'Local',
  },
  {
    id: 'v37',
    sellerId: 'u2',
    shopId: 'd2',
    title: 'Maruti Suzuki Brezza ZXI',
    description: 'Compact SUV, single owner, top features including 360 camera. Very efficient for Patna city traffic.',
    price: 950000,
    vehicleType: 'car',
    brand: 'Maruti Suzuki',
    model: 'Brezza',
    year: 2021,
    fuelType: 'petrol',
    transmission: 'manual',
    kilometersDriven: 24000,
    ownership: '1st',
    city: 'Patna',
    state: 'Bihar',
    images: ['https://images.unsplash.com/photo-1567818735868-e71b99932e29?q=80&w=1200&auto=format&fit=crop'],
    status: 'active',
    isFeatured: true,
    isVerified: true,
    verificationStatus: 'verified',
    listingType: 'premium',
    viewsCount: 3200,
    clicksCount: 450,
    leadsCount: 12,
    priorityScore: 90,
    createdAt: new Date().toISOString(),
    registrationNumber: 'BR01-BZ-1234',
    mileage: '18 kmpl',
    color: 'Magma Grey',
    assemblyType: 'Local',
  },
  {
    id: 'v38',
    sellerId: 'u5',
    shopId: 'd5',
    title: 'Mahindra Scorpio-N Z8L',
    description: 'The Big Daddy of SUVs. 4WD, diesel automatic, sunroof, Sony sound system. King of the road in Raipur.',
    price: 2450000,
    vehicleType: 'car',
    brand: 'Mahindra',
    model: 'Scorpio-N',
    year: 2022,
    fuelType: 'diesel',
    transmission: 'automatic',
    kilometersDriven: 11500,
    ownership: '1st',
    city: 'Raipur',
    state: 'Chhattisgarh',
    images: ['https://images.unsplash.com/photo-1662024103175-015887268875?q=80&w=1200&auto=format&fit=crop'],
    status: 'active',
    isFeatured: true,
    isVerified: true,
    verificationStatus: 'verified',
    listingType: 'premium',
    viewsCount: 8900,
    clicksCount: 1500,
    leadsCount: 35,
    priorityScore: 160,
    createdAt: new Date().toISOString(),
    registrationNumber: 'CG04-SN-0001',
    mileage: '13 kmpl',
    color: 'Deep Forest',
    assemblyType: 'Local',
  },
  {
    id: 'v39',
    sellerId: 'u2',
    shopId: 'd2',
    title: 'Tata Harrier XZA+',
    description: 'Bold design, powerful Kryotec engine, panoramic sunroof. Dark Edition with blacked out wheels.',
    price: 1950000,
    vehicleType: 'car',
    brand: 'Tata',
    model: 'Harrier',
    year: 2021,
    fuelType: 'diesel',
    transmission: 'automatic',
    kilometersDriven: 28000,
    ownership: '1st',
    city: 'Patna',
    state: 'Bihar',
    images: ['https://images.unsplash.com/photo-1605559424843-9e4c228bf1c2?q=80&w=1200&auto=format&fit=crop'],
    status: 'active',
    isFeatured: false,
    isVerified: true,
    verificationStatus: 'verified',
    listingType: 'free',
    viewsCount: 4500,
    clicksCount: 620,
    leadsCount: 10,
    priorityScore: 40,
    createdAt: new Date().toISOString(),
    registrationNumber: 'BR01-HR-5678',
    mileage: '15 kmpl',
    color: 'Oberon Black',
    assemblyType: 'Local',
  },
  {
    id: 'v40',
    sellerId: 'u5',
    shopId: 'd5',
    title: 'Kia Seltos GTS Edition',
    description: 'Style and tech combined. GT line with red accents, ventilated seats, heads-up display.',
    price: 1650000,
    vehicleType: 'car',
    brand: 'Kia',
    model: 'Seltos',
    year: 2022,
    fuelType: 'petrol',
    transmission: 'automatic',
    kilometersDriven: 14000,
    ownership: '1st',
    city: 'Raipur',
    state: 'Chhattisgarh',
    images: ['https://images.unsplash.com/photo-1635843104295-50280145464a?q=80&w=1200&auto=format&fit=crop'],
    status: 'active',
    isFeatured: true,
    isVerified: true,
    verificationStatus: 'verified',
    listingType: 'premium',
    viewsCount: 5200,
    clicksCount: 840,
    leadsCount: 18,
    priorityScore: 120,
    createdAt: new Date().toISOString(),
    registrationNumber: 'CG04-KS-7788',
    mileage: '16 kmpl',
    color: 'Intense Red',
    assemblyType: 'Local',
  },
  {
    id: 'v41',
    sellerId: 'u2',
    shopId: 'd2',
    title: 'Hero Splendor Plus XTEC',
    description: 'The mileage king. Digital console, Bluetooth connectivity, single owner, fresh condition.',
    price: 65000,
    vehicleType: 'bike',
    brand: 'Hero',
    model: 'Splendor Plus',
    year: 2023,
    fuelType: 'petrol',
    transmission: 'manual',
    kilometersDriven: 3500,
    ownership: '1st',
    city: 'Patna',
    state: 'Bihar',
    images: ['https://images.unsplash.com/photo-1558981403-c5f9899a28bc?q=80&w=1200&auto=format&fit=crop'],
    status: 'active',
    isFeatured: false,
    isVerified: true,
    verificationStatus: 'verified',
    listingType: 'free',
    viewsCount: 2800,
    clicksCount: 520,
    leadsCount: 8,
    priorityScore: 35,
    createdAt: new Date().toISOString(),
    registrationNumber: 'BR01-SP-1122',
    mileage: '70 kmpl',
    color: 'Black with Silver',
    assemblyType: 'Local',
  },
  {
    id: 'v42',
    sellerId: 'u5',
    shopId: 'd5',
    title: 'Toyota Innova Crysta ZX',
    description: 'The reliability champion. 7-seater lux comfort, diesel automatic, always serviced at showroom.',
    price: 2150000,
    vehicleType: 'car',
    brand: 'Toyota',
    model: 'Innova Crysta',
    year: 2020,
    fuelType: 'diesel',
    transmission: 'automatic',
    kilometersDriven: 55000,
    ownership: '1st',
    city: 'Raipur',
    state: 'Chhattisgarh',
    images: ['https://images.unsplash.com/photo-1621007947382-bb3c3994e3fb?q=80&w=1200&auto=format&fit=crop'],
    status: 'active',
    isFeatured: true,
    isVerified: true,
    verificationStatus: 'verified',
    listingType: 'sponsored',
    viewsCount: 12000,
    clicksCount: 2100,
    leadsCount: 48,
    priorityScore: 190,
    createdAt: new Date().toISOString(),
    registrationNumber: 'CG04-IC-9999',
    mileage: '12 kmpl',
    color: 'Super White',
    assemblyType: 'Local',
  },
  {
    id: 'v43',
    sellerId: 'u2',
    shopId: 'd2',
    title: 'Honda Amaze VX CVT',
    description: 'Smooth automatic sedan, perfect for city commute. Beige interior, well maintained.',
    price: 750000,
    vehicleType: 'car',
    brand: 'Honda',
    model: 'Amaze',
    year: 2021,
    fuelType: 'petrol',
    transmission: 'automatic',
    kilometersDriven: 18000,
    ownership: '1st',
    city: 'Patna',
    state: 'Bihar',
    images: ['https://images.unsplash.com/photo-1583121274602-3e2820c69888?q=80&w=1200&auto=format&fit=crop'],
    status: 'active',
    isFeatured: false,
    isVerified: true,
    verificationStatus: 'verified',
    listingType: 'free',
    viewsCount: 3100,
    clicksCount: 450,
    leadsCount: 10,
    priorityScore: 45,
    createdAt: new Date().toISOString(),
    registrationNumber: 'BR01-AM-3344',
    mileage: '18 kmpl',
    color: 'Radiant Red',
    assemblyType: 'Local',
  },
    {
    id: 'v1',
    sellerId: 'u1',
    shopId: 'd1',
    title: 'Maruti Suzuki Swift VXI',
    description: 'Excellent condition, single owner, well maintained.',
    price: 450000,
    vehicleType: 'car',
    brand: 'Maruti Suzuki',
    model: 'Swift',
    year: 2019,
    fuelType: 'petrol',
    transmission: 'manual',
    kilometersDriven: 35000,
    ownership: '1st',
    color: 'Red',
    assemblyType: 'Local',
    city: 'Bhopal',
    state: 'Madhya Pradesh',
    images: ['https://images.unsplash.com/photo-1567818735868-e71b99932e29?q=80&w=1000&auto=format&fit=crop', 'https://picsum.photos/seed/car1-2/800/600'],
    engineStartVideo: 'https://www.w3schools.com/html/mov_bbb.mp4',
    engineSoundVideo: 'https://www.w3schools.com/html/movie.mp4',
    walkaroundVideo: 'https://www.w3schools.com/html/mov_bbb.mp4',
    status: 'active',
    isFeatured: true,
    isVerified: true,
    verificationStatus: 'verified',
    listingType: 'sponsored',
    viewsCount: 1200,
    clicksCount: 450,
    leadsCount: 12,
    priorityScore: 100,
    createdAt: new Date().toISOString(),
    registrationNumber: 'MP04-AB-1234',
    mileage: '22 kmpl',
    priceHistory: [
      { date: '2024-01-15', price: 680000 },
      { date: '2024-02-01', price: 675000 },
      { date: '2024-02-15', price: 660000 },
      { date: '2024-03-01', price: 655000 },
      { date: '2024-03-15', price: 650000 },
      { date: '2024-04-01', price: 645000 },
    ],
  },
  {
    id: 'v2',
    sellerId: 'u2',
    shopId: 'd2',
    title: 'Royal Enfield Classic 350',
    description: 'Gunmetal Grey, low mileage, timely serviced.',
    price: 165000,
    vehicleType: 'bike',
    brand: 'Royal Enfield',
    model: 'Classic 350',
    year: 2021,
    fuelType: 'petrol',
    transmission: 'manual',
    kilometersDriven: 12000,
    ownership: '1st',
    city: 'Patna',
    state: 'Bihar',
    images: ['https://images.unsplash.com/photo-1558981806-ec527fa84c39?q=80&w=1000&auto=format&fit=crop'],
    status: 'active',
    isFeatured: false,
    isVerified: true,
    verificationStatus: 'verified',
    listingType: 'premium',
    viewsCount: 850,
    clicksCount: 120,
    leadsCount: 5,
    priorityScore: 70,
    createdAt: new Date().toISOString(),
    registrationNumber: 'BR01-XY-5678',
    mileage: '35 kmpl',
    priceHistory: [
      { date: '2024-01-20', price: 175000 },
      { date: '2024-02-10', price: 172000 },
      { date: '2024-03-05', price: 170000 },
      { date: '2024-04-12', price: 165000 },
    ],
    color: 'Gunmetal Grey',
    assemblyType: 'Local',
  },
  {
    id: 'v3',
    sellerId: 'u3',
    title: 'Hyundai i20 Asta',
    description: 'Top model with sunroof, very clean interior.',
    price: 620000,
    vehicleType: 'car',
    brand: 'Hyundai',
    model: 'i20',
    year: 2020,
    fuelType: 'diesel',
    transmission: 'manual',
    kilometersDriven: 45000,
    ownership: '2nd',
    city: 'Raipur',
    state: 'Chhattisgarh',
    images: ['https://images.unsplash.com/photo-1541899481282-d53bffe3c35d?q=80&w=1000&auto=format&fit=crop'],
    status: 'active',
    isFeatured: true,
    isVerified: false,
    verificationStatus: 'pending',
    listingType: 'featured',
    viewsCount: 500,
    clicksCount: 85,
    leadsCount: 3,
    priorityScore: 85,
    createdAt: new Date().toISOString(),
    registrationNumber: 'CG04-MN-9012',
    mileage: '18 kmpl',
    color: 'White',
    assemblyType: 'Local',
  },
  {
    id: 'v4',
    sellerId: 'u4',
    title: 'Honda Civic RS',
    description: 'Sporty look, powerful engine, red hot color. RS variant with blacked out elements.',
    price: 1200000,
    vehicleType: 'car',
    brand: 'Honda',
    model: 'Civic',
    year: 2022,
    fuelType: 'petrol',
    transmission: 'automatic',
    kilometersDriven: 8000,
    ownership: '1st',
    city: 'Bhopal',
    state: 'Madhya Pradesh',
    images: ['https://images.unsplash.com/photo-1606152421802-db97b9c7a11b?q=80&w=1000&auto=format&fit=crop', 'https://images.unsplash.com/photo-1594070319944-7c0c63146b77?q=80&w=1000&auto=format&fit=crop'],
    status: 'active',
    isFeatured: false,
    isVerified: true,
    verificationStatus: 'verified',
    listingType: 'free',
    viewsCount: 2500,
    clicksCount: 150,
    leadsCount: 8,
    priorityScore: 50,
    createdAt: new Date().toISOString(),
    registrationNumber: 'MP04-CD-3456',
    mileage: '15 kmpl',
    color: 'Red',
    assemblyType: 'Local',
  },
  {
    id: 'v5',
    sellerId: 'u5',
    title: 'Ford EcoSport Titanium',
    description: 'Compact SUV, great for city and highway.',
    price: 850000,
    vehicleType: 'car',
    brand: 'Ford',
    model: 'EcoSport',
    year: 2021,
    fuelType: 'diesel',
    transmission: 'manual',
    kilometersDriven: 15000,
    ownership: '1st',
    city: 'Patna',
    state: 'Bihar',
    images: ['https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?q=80&w=1000&auto=format&fit=crop'],
    status: 'active',
    isFeatured: true,
    isVerified: true,
    verificationStatus: 'verified',
    listingType: 'premium',
    viewsCount: 1800,
    clicksCount: 220,
    leadsCount: 11,
    priorityScore: 80,
    createdAt: new Date().toISOString(),
    registrationNumber: 'BR01-EF-7890',
    mileage: '20 kmpl',
    color: 'Blue',
    assemblyType: 'Local',
  },
  {
    id: 'v6',
    sellerId: 'u6',
    title: 'Toyota Fortuner Sigma 4',
    description: 'Powerful SUV, 4x4, immaculate condition.',
    price: 3200000,
    vehicleType: 'car',
    brand: 'Toyota',
    model: 'Fortuner',
    year: 2021,
    fuelType: 'diesel',
    transmission: 'automatic',
    kilometersDriven: 25000,
    ownership: '1st',
    city: 'Bhopal',
    state: 'Madhya Pradesh',
    images: ['https://images.unsplash.com/photo-1606611013016-969c19ba27bb?q=80&w=1000&auto=format&fit=crop'],
    status: 'active',
    isFeatured: true,
    isVerified: true,
    verificationStatus: 'verified',
    listingType: 'sponsored',
    viewsCount: 4500,
    clicksCount: 800,
    leadsCount: 45,
    priorityScore: 110,
    createdAt: new Date().toISOString(),
    registrationNumber: 'MP04-GH-1122',
    mileage: '12 kmpl',
  },
  {
    id: 'v7',
    sellerId: 'u7',
    title: 'Mahindra Thar LX',
    description: 'Hard top, diesel, 4x4, off-road ready.',
    price: 1450000,
    vehicleType: 'car',
    brand: 'Mahindra',
    model: 'Thar',
    year: 2022,
    fuelType: 'diesel',
    transmission: 'manual',
    kilometersDriven: 10000,
    ownership: '1st',
    city: 'Raipur',
    state: 'Chhattisgarh',
    images: ['https://images.unsplash.com/photo-1662024103175-015887268875?q=80&w=1000&auto=format&fit=crop'],
    status: 'active',
    isFeatured: true,
    isVerified: true,
    verificationStatus: 'verified',
    listingType: 'free',
    clicksCount: 0,
    leadsCount: 0,
    priorityScore: 0,
    viewsCount: 3200,
    createdAt: new Date().toISOString(),
    registrationNumber: 'CG04-JK-3344',
    mileage: '14 kmpl',
  },
  {
    id: 'v8',
    sellerId: 'u8',
    title: 'Tata Nexon EV Max',
    description: 'Electric SUV, long range, eco-friendly.',
    price: 1550000,
    vehicleType: 'car',
    brand: 'Tata',
    model: 'Nexon EV',
    year: 2023,
    fuelType: 'electric',
    transmission: 'automatic',
    kilometersDriven: 5000,
    ownership: '1st',
    city: 'Bhopal',
    state: 'Madhya Pradesh',
    images: ['https://images.unsplash.com/photo-1617788138017-80ad40651399?q=80&w=1000&auto=format&fit=crop'],
    status: 'active',
    isFeatured: false,
    isVerified: true,
    verificationStatus: 'rejected',
    listingType: 'free',
    clicksCount: 0,
    leadsCount: 0,
    priorityScore: 0,
    viewsCount: 1500,
    createdAt: new Date().toISOString(),
    registrationNumber: 'MP04-LM-5566',
    mileage: '450 km/charge',
    color: 'Teal Blue',
    assemblyType: 'Local',
  },
  {
    id: 'v9',
    sellerId: 'u9',
    title: 'KTM Duke 390',
    description: 'Fast and agile, orange beast, well maintained.',
    price: 240000,
    vehicleType: 'bike',
    brand: 'KTM',
    model: 'Duke 390',
    year: 2022,
    fuelType: 'petrol',
    transmission: 'manual',
    kilometersDriven: 6000,
    ownership: '1st',
    city: 'Patna',
    state: 'Bihar',
    images: ['https://images.unsplash.com/photo-1568772585407-9361f9bf3a87?q=80&w=1000&auto=format&fit=crop'],
    status: 'active',
    isFeatured: false,
    isVerified: true,
    verificationStatus: 'verified',
    listingType: 'free',
    clicksCount: 0,
    leadsCount: 0,
    priorityScore: 0,
    viewsCount: 2100,
    createdAt: new Date().toISOString(),
    registrationNumber: 'BR01-PQ-1122',
    mileage: '45 kmpl',
  },
  {
    id: 'v10',
    sellerId: 'u10',
    title: 'Honda City ZX',
    description: 'Premium sedan, sunroof, leather seats.',
    price: 1100000,
    vehicleType: 'car',
    brand: 'Honda',
    model: 'City',
    year: 2021,
    fuelType: 'petrol',
    transmission: 'automatic',
    kilometersDriven: 18000,
    ownership: '1st',
    city: 'Bhopal',
    state: 'Madhya Pradesh',
    images: ['https://images.unsplash.com/photo-1583121274602-3e2820c69888?q=80&w=1000&auto=format&fit=crop'],
    status: 'active',
    isFeatured: true,
    isVerified: true,
    verificationStatus: 'verified',
    listingType: 'free',
    clicksCount: 0,
    leadsCount: 0,
    priorityScore: 0,
    viewsCount: 1900,
    createdAt: new Date().toISOString(),
    registrationNumber: 'MP04-RS-3344',
    mileage: '16 kmpl',
  },
  {
    id: 'v11',
    sellerId: 'u11',
    title: 'BMW 3 Series 320d',
    description: 'Luxury sedan, sunroof, M-Sport package, low mileage.',
    price: 3800000,
    vehicleType: 'car',
    brand: 'BMW',
    model: '3 Series',
    year: 2022,
    fuelType: 'diesel',
    transmission: 'automatic',
    kilometersDriven: 12000,
    ownership: '1st',
    city: 'Bhopal',
    state: 'Madhya Pradesh',
    images: ['https://images.unsplash.com/photo-1555215695-3004980ad54e?q=80&w=1000&auto=format&fit=crop'],
    status: 'active',
    isFeatured: true,
    isVerified: true,
    verificationStatus: 'verified',
    listingType: 'premium',
    clicksCount: 450,
    leadsCount: 25,
    priorityScore: 25,
    viewsCount: 5200,
    createdAt: new Date().toISOString(),
    registrationNumber: 'MP04-BM-7788',
    mileage: '14 kmpl',
  },
  {
    id: 'v12',
    sellerId: 'u12',
    title: 'Mercedes-Benz C-Class',
    description: 'Elegant white, panoramic sunroof, premium audio.',
    price: 4200000,
    vehicleType: 'car',
    brand: 'Mercedes-Benz',
    model: 'C-Class',
    year: 2021,
    fuelType: 'petrol',
    transmission: 'automatic',
    kilometersDriven: 15000,
    ownership: '1st',
    city: 'Raipur',
    state: 'Chhattisgarh',
    images: ['https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?q=80&w=1000&auto=format&fit=crop'],
    status: 'active',
    isFeatured: true,
    isVerified: true,
    verificationStatus: 'verified',
    listingType: 'free',
    clicksCount: 0,
    leadsCount: 0,
    priorityScore: 0,
    viewsCount: 4800,
    createdAt: new Date().toISOString(),
    registrationNumber: 'CG04-MB-9900',
    mileage: '12 kmpl',
  },
  {
    id: 'v13',
    sellerId: 'u13',
    title: 'Audi Q5 Quattro',
    description: 'All-wheel drive SUV, powerful engine, luxury interior.',
    price: 3500000,
    vehicleType: 'car',
    brand: 'Audi',
    model: 'Q5',
    year: 2020,
    fuelType: 'diesel',
    transmission: 'automatic',
    kilometersDriven: 28000,
    ownership: '1st',
    city: 'Bhopal',
    state: 'Madhya Pradesh',
    images: ['https://images.unsplash.com/photo-1541899481282-d53bffe3c35d?q=80&w=1000&auto=format&fit=crop'],
    status: 'active',
    isFeatured: false,
    isVerified: true,
    verificationStatus: 'verified',
    listingType: 'free',
    clicksCount: 0,
    leadsCount: 0,
    priorityScore: 0,
    viewsCount: 3100,
    createdAt: new Date().toISOString(),
    registrationNumber: 'MP04-AU-1122',
    mileage: '13 kmpl',
  },
  {
    id: 'v14',
    sellerId: 'u14',
    title: 'Kawasaki Ninja 650',
    description: 'Sport touring bike, green beast, very fast.',
    price: 550000,
    vehicleType: 'bike',
    brand: 'Kawasaki',
    model: 'Ninja 650',
    year: 2022,
    fuelType: 'petrol',
    transmission: 'manual',
    kilometersDriven: 4000,
    ownership: '1st',
    city: 'Patna',
    state: 'Bihar',
    images: ['https://images.unsplash.com/photo-1568772585407-9361f9bf3a87?q=80&w=1000&auto=format&fit=crop'],
    status: 'active',
    isFeatured: true,
    isVerified: true,
    verificationStatus: 'verified',
    listingType: 'featured',
    clicksCount: 600,
    leadsCount: 30,
    priorityScore: 50,
    viewsCount: 2800,
    createdAt: new Date().toISOString(),
    registrationNumber: 'BR01-KW-5566',
    mileage: '25 kmpl',
  },
  {
    id: 'v15',
    sellerId: 'u15',
    title: 'Je Jeep Compass Limited',
    description: 'Rugged SUV, excellent build quality, diesel engine.',
    price: 1800000,
    vehicleType: 'car',
    brand: 'Jeep',
    model: 'Compass',
    year: 2021,
    fuelType: 'diesel',
    transmission: 'automatic',
    kilometersDriven: 22000,
    ownership: '1st',
    city: 'Bhopal',
    state: 'Madhya Pradesh',
    images: ['https://images.unsplash.com/photo-1609521263047-f8f205293f24?q=80&w=1000&auto=format&fit=crop'],
    status: 'active',
    isFeatured: false,
    isVerified: true,
    verificationStatus: 'verified',
    listingType: 'free',
    clicksCount: 0,
    leadsCount: 0,
    priorityScore: 0,
    viewsCount: 1700,
    createdAt: new Date().toISOString(),
    registrationNumber: 'MP04-JP-7788',
    mileage: '15 kmpl',
  }
];
