import { Vehicle, Dealer } from '../types';

export const MOCK_DEALERS: Dealer[] = [
  {
    id: 'd1',
    userId: 'u1',
    shopName: 'Bhopal Motors',
    description: 'Trusted dealer in Bhopal for over 10 years.',
    shopImages: ['https://picsum.photos/seed/shop1/800/600'],
    latitude: 23.2599,
    longitude: 77.4126,
    address: 'MP Nagar Zone 1',
    city: 'Bhopal',
    state: 'Madhya Pradesh',
    pincode: '462011',
    isVerified: true,
    rating: 4.5,
    totalReviews: 120,
  },
  {
    id: 'd2',
    userId: 'u2',
    shopName: 'Patna Wheels',
    description: 'Best collection of pre-owned bikes and cars in Patna.',
    shopImages: ['https://picsum.photos/seed/shop2/800/600'],
    latitude: 25.5941,
    longitude: 85.1376,
    address: 'Boring Road',
    city: 'Patna',
    state: 'Bihar',
    pincode: '800001',
    isVerified: true,
    rating: 4.2,
    totalReviews: 85,
  }
];

export const MOCK_VEHICLES: Vehicle[] = [
  {
    id: 'v1',
    sellerId: 'u1',
    dealerId: 'd1',
    title: 'Maruti Suzuki Swift VXI',
    description: 'Excellent condition, single owner, well maintained.',
    price: 450000,
    vehicleType: 'car',
    brand: 'Maruti Suzuki',
    model: 'Swift',
    year: 2019,
    fuelType: 'petrol',
    transmission: 'manual',
    kilometersDriven: 35000,
    ownership: '1st',
    city: 'Bhopal',
    state: 'Madhya Pradesh',
    images: ['https://images.unsplash.com/photo-1567818735868-e71b99932e29?q=80&w=1000&auto=format&fit=crop', 'https://picsum.photos/seed/car1-2/800/600'],
    status: 'active',
    isFeatured: true,
    isVerified: true,
    viewsCount: 1200,
    createdAt: new Date().toISOString(),
    registrationNumber: 'MP04-AB-1234',
    mileage: '22 kmpl',
  },
  {
    id: 'v2',
    sellerId: 'u2',
    dealerId: 'd2',
    title: 'Royal Enfield Classic 350',
    description: 'Gunmetal Grey, low mileage, timely serviced.',
    price: 165000,
    vehicleType: 'bike',
    brand: 'Royal Enfield',
    model: 'Classic 350',
    year: 2021,
    fuelType: 'petrol',
    transmission: 'manual',
    kilometersDriven: 12000,
    ownership: '1st',
    city: 'Patna',
    state: 'Bihar',
    images: ['https://images.unsplash.com/photo-1558981806-ec527fa84c39?q=80&w=1000&auto=format&fit=crop'],
    status: 'active',
    isFeatured: false,
    isVerified: true,
    viewsCount: 850,
    createdAt: new Date().toISOString(),
    registrationNumber: 'BR01-XY-5678',
    mileage: '35 kmpl',
  },
  {
    id: 'v3',
    sellerId: 'u3',
    title: 'Hyundai i20 Asta',
    description: 'Top model with sunroof, very clean interior.',
    price: 620000,
    vehicleType: 'car',
    brand: 'Hyundai',
    model: 'i20',
    year: 2020,
    fuelType: 'diesel',
    transmission: 'manual',
    kilometersDriven: 45000,
    ownership: '2nd',
    city: 'Raipur',
    state: 'Chhattisgarh',
    images: ['https://images.unsplash.com/photo-1541899481282-d53bffe3c35d?q=80&w=1000&auto=format&fit=crop'],
    status: 'active',
    isFeatured: true,
    isVerified: false,
    viewsCount: 500,
    createdAt: new Date().toISOString(),
    registrationNumber: 'CG04-MN-9012',
    mileage: '18 kmpl',
  },
  {
    id: 'v4',
    sellerId: 'u4',
    title: 'Honda Civic RS',
    description: 'Sporty look, powerful engine, red hot color. RS variant with blacked out elements.',
    price: 1200000,
    vehicleType: 'car',
    brand: 'Honda',
    model: 'Civic',
    year: 2022,
    fuelType: 'petrol',
    transmission: 'automatic',
    kilometersDriven: 8000,
    ownership: '1st',
    city: 'Bhopal',
    state: 'Madhya Pradesh',
    images: ['https://images.unsplash.com/photo-1606152421802-db97b9c7a11b?q=80&w=1000&auto=format&fit=crop', 'https://images.unsplash.com/photo-1594070319944-7c0c63146b77?q=80&w=1000&auto=format&fit=crop'],
    status: 'active',
    isFeatured: false,
    isVerified: true,
    viewsCount: 2500,
    createdAt: new Date().toISOString(),
    registrationNumber: 'MP04-CD-3456',
    mileage: '15 kmpl',
  },
  {
    id: 'v5',
    sellerId: 'u5',
    title: 'Ford EcoSport Titanium',
    description: 'Compact SUV, great for city and highway.',
    price: 850000,
    vehicleType: 'car',
    brand: 'Ford',
    model: 'EcoSport',
    year: 2021,
    fuelType: 'diesel',
    transmission: 'manual',
    kilometersDriven: 15000,
    ownership: '1st',
    city: 'Patna',
    state: 'Bihar',
    images: ['https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?q=80&w=1000&auto=format&fit=crop'],
    status: 'active',
    isFeatured: true,
    isVerified: true,
    viewsCount: 1800,
    createdAt: new Date().toISOString(),
    registrationNumber: 'BR01-EF-7890',
    mileage: '20 kmpl',
  },
  {
    id: 'v6',
    sellerId: 'u6',
    title: 'Toyota Fortuner Sigma 4',
    description: 'Powerful SUV, 4x4, immaculate condition.',
    price: 3200000,
    vehicleType: 'car',
    brand: 'Toyota',
    model: 'Fortuner',
    year: 2021,
    fuelType: 'diesel',
    transmission: 'automatic',
    kilometersDriven: 25000,
    ownership: '1st',
    city: 'Bhopal',
    state: 'Madhya Pradesh',
    images: ['https://images.unsplash.com/photo-1606611013016-969c19ba27bb?q=80&w=1000&auto=format&fit=crop'],
    status: 'active',
    isFeatured: true,
    isVerified: true,
    viewsCount: 4500,
    createdAt: new Date().toISOString(),
    registrationNumber: 'MP04-GH-1122',
    mileage: '12 kmpl',
  },
  {
    id: 'v7',
    sellerId: 'u7',
    title: 'Mahindra Thar LX',
    description: 'Hard top, diesel, 4x4, off-road ready.',
    price: 1450000,
    vehicleType: 'car',
    brand: 'Mahindra',
    model: 'Thar',
    year: 2022,
    fuelType: 'diesel',
    transmission: 'manual',
    kilometersDriven: 10000,
    ownership: '1st',
    city: 'Raipur',
    state: 'Chhattisgarh',
    images: ['https://images.unsplash.com/photo-1662024103175-015887268875?q=80&w=1000&auto=format&fit=crop'],
    status: 'active',
    isFeatured: true,
    isVerified: true,
    viewsCount: 3200,
    createdAt: new Date().toISOString(),
    registrationNumber: 'CG04-JK-3344',
    mileage: '14 kmpl',
  },
  {
    id: 'v8',
    sellerId: 'u8',
    title: 'Tata Nexon EV Max',
    description: 'Electric SUV, long range, eco-friendly.',
    price: 1550000,
    vehicleType: 'car',
    brand: 'Tata',
    model: 'Nexon EV',
    year: 2023,
    fuelType: 'electric',
    transmission: 'automatic',
    kilometersDriven: 5000,
    ownership: '1st',
    city: 'Bhopal',
    state: 'Madhya Pradesh',
    images: ['https://images.unsplash.com/photo-1617788138017-80ad40651399?q=80&w=1000&auto=format&fit=crop'],
    status: 'active',
    isFeatured: false,
    isVerified: true,
    viewsCount: 1500,
    createdAt: new Date().toISOString(),
    registrationNumber: 'MP04-LM-5566',
    mileage: '450 km/charge',
  },
  {
    id: 'v9',
    sellerId: 'u9',
    title: 'KTM Duke 390',
    description: 'Fast and agile, orange beast, well maintained.',
    price: 240000,
    vehicleType: 'bike',
    brand: 'KTM',
    model: 'Duke 390',
    year: 2022,
    fuelType: 'petrol',
    transmission: 'manual',
    kilometersDriven: 6000,
    ownership: '1st',
    city: 'Patna',
    state: 'Bihar',
    images: ['https://images.unsplash.com/photo-1568772585407-9361f9bf3a87?q=80&w=1000&auto=format&fit=crop'],
    status: 'active',
    isFeatured: false,
    isVerified: true,
    viewsCount: 2100,
    createdAt: new Date().toISOString(),
    registrationNumber: 'BR01-PQ-1122',
    mileage: '45 kmpl',
  },
  {
    id: 'v10',
    sellerId: 'u10',
    title: 'Honda City ZX',
    description: 'Premium sedan, sunroof, leather seats.',
    price: 1100000,
    vehicleType: 'car',
    brand: 'Honda',
    model: 'City',
    year: 2021,
    fuelType: 'petrol',
    transmission: 'automatic',
    kilometersDriven: 18000,
    ownership: '1st',
    city: 'Bhopal',
    state: 'Madhya Pradesh',
    images: ['https://images.unsplash.com/photo-1583121274602-3e2820c69888?q=80&w=1000&auto=format&fit=crop'],
    status: 'active',
    isFeatured: true,
    isVerified: true,
    viewsCount: 1900,
    createdAt: new Date().toISOString(),
    registrationNumber: 'MP04-RS-3344',
    mileage: '16 kmpl',
  },
  {
    id: 'v11',
    sellerId: 'u11',
    title: 'BMW 3 Series 320d',
    description: 'Luxury sedan, sunroof, M-Sport package, low mileage.',
    price: 3800000,
    vehicleType: 'car',
    brand: 'BMW',
    model: '3 Series',
    year: 2022,
    fuelType: 'diesel',
    transmission: 'automatic',
    kilometersDriven: 12000,
    ownership: '1st',
    city: 'Bhopal',
    state: 'Madhya Pradesh',
    images: ['https://images.unsplash.com/photo-1555215695-3004980ad54e?q=80&w=1000&auto=format&fit=crop'],
    status: 'active',
    isFeatured: true,
    isVerified: true,
    viewsCount: 5200,
    createdAt: new Date().toISOString(),
    registrationNumber: 'MP04-BM-7788',
    mileage: '14 kmpl',
  },
  {
    id: 'v12',
    sellerId: 'u12',
    title: 'Mercedes-Benz C-Class',
    description: 'Elegant white, panoramic sunroof, premium audio.',
    price: 4200000,
    vehicleType: 'car',
    brand: 'Mercedes-Benz',
    model: 'C-Class',
    year: 2021,
    fuelType: 'petrol',
    transmission: 'automatic',
    kilometersDriven: 15000,
    ownership: '1st',
    city: 'Raipur',
    state: 'Chhattisgarh',
    images: ['https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?q=80&w=1000&auto=format&fit=crop'],
    status: 'active',
    isFeatured: true,
    isVerified: true,
    viewsCount: 4800,
    createdAt: new Date().toISOString(),
    registrationNumber: 'CG04-MB-9900',
    mileage: '12 kmpl',
  },
  {
    id: 'v13',
    sellerId: 'u13',
    title: 'Audi Q5 Quattro',
    description: 'All-wheel drive SUV, powerful engine, luxury interior.',
    price: 3500000,
    vehicleType: 'car',
    brand: 'Audi',
    model: 'Q5',
    year: 2020,
    fuelType: 'diesel',
    transmission: 'automatic',
    kilometersDriven: 28000,
    ownership: '1st',
    city: 'Bhopal',
    state: 'Madhya Pradesh',
    images: ['https://images.unsplash.com/photo-1541899481282-d53bffe3c35d?q=80&w=1000&auto=format&fit=crop'],
    status: 'active',
    isFeatured: false,
    isVerified: true,
    viewsCount: 3100,
    createdAt: new Date().toISOString(),
    registrationNumber: 'MP04-AU-1122',
    mileage: '13 kmpl',
  },
  {
    id: 'v14',
    sellerId: 'u14',
    title: 'Kawasaki Ninja 650',
    description: 'Sport touring bike, green beast, very fast.',
    price: 550000,
    vehicleType: 'bike',
    brand: 'Kawasaki',
    model: 'Ninja 650',
    year: 2022,
    fuelType: 'petrol',
    transmission: 'manual',
    kilometersDriven: 4000,
    ownership: '1st',
    city: 'Patna',
    state: 'Bihar',
    images: ['https://images.unsplash.com/photo-1568772585407-9361f9bf3a87?q=80&w=1000&auto=format&fit=crop'],
    status: 'active',
    isFeatured: true,
    isVerified: true,
    viewsCount: 2800,
    createdAt: new Date().toISOString(),
    registrationNumber: 'BR01-KW-5566',
    mileage: '25 kmpl',
  },
  {
    id: 'v15',
    sellerId: 'u15',
    title: 'Jeep Compass Limited',
    description: 'Rugged SUV, excellent build quality, diesel engine.',
    price: 1800000,
    vehicleType: 'car',
    brand: 'Jeep',
    model: 'Compass',
    year: 2021,
    fuelType: 'diesel',
    transmission: 'automatic',
    kilometersDriven: 22000,
    ownership: '1st',
    city: 'Bhopal',
    state: 'Madhya Pradesh',
    images: ['https://images.unsplash.com/photo-1609521263047-f8f205293f24?q=80&w=1000&auto=format&fit=crop'],
    status: 'active',
    isFeatured: false,
    isVerified: true,
    viewsCount: 1700,
    createdAt: new Date().toISOString(),
    registrationNumber: 'MP04-JP-7788',
    mileage: '15 kmpl',
  }
];
